"""
thehive.py — TheHive 5 Case Management Integration
====================================================
Creates a TheHive case for every incident that reaches the audit node,
giving SOC analysts a persistent case lifecycle (open → in-progress → closed)
beyond the ephemeral HITL card in the dashboard.

Configuration (all optional — module is a no-op if THEHIVE_URL is unset):
  THEHIVE_URL      — e.g. http://thehive:9000
  THEHIVE_API_KEY  — API key from TheHive admin panel (Organisation → API keys)
  THEHIVE_ORG      — organisation name (default "SOC")

TheHive 5 REST API reference:
  POST /api/v1/case                    — create case
  POST /api/v1/case/{id}/observable   — attach an observable (IP, hash, etc.)

Non-fatal: a TheHive outage must never block the main pipeline. All calls
are wrapped in try/except and return None on failure.
"""

import os
from datetime import datetime, timezone

import httpx

_THEHIVE_URL = os.getenv("THEHIVE_URL",     "")
_THEHIVE_KEY = os.getenv("THEHIVE_API_KEY", "")
_THEHIVE_ORG = os.getenv("THEHIVE_ORG",     "SOC")
_TIMEOUT     = 5.0


def _headers() -> dict:
    return {
        "Authorization": f"Bearer {_THEHIVE_KEY}",
        "Content-Type":  "application/json",
        "X-Organisation": _THEHIVE_ORG,
    }


def _severity_to_int(score: float) -> int:
    """Map 0-10 composite threat score to TheHive severity (1=Low, 2=Medium, 3=High, 4=Critical)."""
    if score >= 9.0:
        return 4
    if score >= 7.0:
        return 3
    if score >= 4.0:
        return 2
    return 1


def create_case(
    incident_id:      str,
    alert_data:       dict,
    threat_score:     float,
    mitre_techniques: list[str],
    remediation:      str,
) -> str | None:
    """
    Create a TheHive case for a processed incident.
    Returns the case ID on success, None on failure or if TheHive is not configured.

    The case includes:
      - Title: alert type + source IP
      - Description: full audit summary in Markdown
      - Severity: mapped from composite threat score
      - Tags: alert vendor, MITRE technique IDs, remediation status
      - Observable: source IP as a network/ip observable
    """
    if not _THEHIVE_URL or not _THEHIVE_KEY:
        return None

    source_ip  = alert_data.get("source_ip", "unknown")
    alert_type = alert_data.get("alert_type", "Unknown")
    vendor     = alert_data.get("vendor", "unknown")
    now        = datetime.now(timezone.utc).isoformat()

    mitre_ids = [t.split(" ")[0] for t in mitre_techniques]

    description = (
        f"## Incident {incident_id}\n\n"
        f"**Source IP:** `{source_ip}`  \n"
        f"**Alert type:** {alert_type}  \n"
        f"**Vendor:** {vendor}  \n"
        f"**Composite threat score:** {threat_score:.1f}/10  \n"
        f"**Remediation:** {remediation}  \n\n"
        f"### MITRE ATT&CK Techniques\n"
        + "\n".join(f"- {t}" for t in mitre_techniques)
        + f"\n\n_Auto-generated by agentic-SOC-operator at {now}_"
    )

    case_body = {
        "title":       f"[{vendor}] {alert_type} from {source_ip}",
        "description": description,
        "severity":    _severity_to_int(threat_score),
        "startDate":   int(datetime.now(timezone.utc).timestamp() * 1000),
        "tags":        [vendor, alert_type] + mitre_ids + [f"score:{threat_score:.1f}"],
        "flag":        threat_score >= 9.0,   # flag critical incidents
        "status":      "New",
        "tlp":         2,    # TLP:AMBER — internal distribution only
        "pap":         2,    # PAP:AMBER
    }

    try:
        with httpx.Client(timeout=_TIMEOUT) as c:
            r = c.post(
                f"{_THEHIVE_URL.rstrip('/')}/api/v1/case",
                json=case_body,
                headers=_headers(),
            )
            r.raise_for_status()
            case_id = r.json().get("_id", "")
            print(f"[TheHive] Case created: {case_id} for incident {incident_id}")

            # Attach the source IP as an observable
            if case_id:
                _attach_observable(c, case_id, source_ip, threat_score)

            return case_id

    except Exception as e:
        print(f"[TheHive] Case creation failed (non-fatal): {e}")
        return None


def _attach_observable(client: httpx.Client, case_id: str, ip: str, score: float) -> None:
    """Attach the malicious IP address as a TheHive observable linked to the case."""
    obs_body = {
        "dataType":  "ip",
        "data":      ip,
        "message":   f"Malicious source IP — composite score {score:.1f}/10",
        "tlp":       2,
        "ioc":       True,
        "tags":      ["soar-auto-enriched"],
    }
    try:
        r = client.post(
            f"{_THEHIVE_URL.rstrip('/')}/api/v1/case/{case_id}/observable",
            json=obs_body,
            headers=_headers(),
        )
        r.raise_for_status()
    except Exception as e:
        print(f"[TheHive] Observable attach failed (non-fatal): {e}")
