from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, BaseLoader

from ..core.models import FindingResult

log = logging.getLogger(__name__)

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AegisLoop — Purple Team Report</title>
<style>
  body { font-family: 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 2rem; }
  h1   { color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: .5rem; }
  h2   { color: #8b949e; font-size: 1rem; font-weight: normal; }
  .meta { display: flex; gap: 2rem; margin: 1rem 0 2rem; font-size: .85rem; color: #8b949e; }
  table { width: 100%; border-collapse: collapse; font-size: .9rem; }
  th    { background: #161b22; color: #58a6ff; text-align: left; padding: .6rem 1rem; border-bottom: 2px solid #30363d; }
  td    { padding: .55rem 1rem; border-bottom: 1px solid #21262d; vertical-align: top; }
  tr:hover td { background: #161b22; }
  .BLOCKED  { color: #3fb950; font-weight: 600; }
  .BYPASSED { color: #f85149; font-weight: 600; }
  .PARTIAL  { color: #d29922; font-weight: 600; }
  .UNTESTED { color: #8b949e; }
  .CRITICAL { color: #f85149; }
  .HIGH     { color: #d29922; }
  .MEDIUM   { color: #e3b341; }
  .LOW      { color: #3fb950; }
  .evidence { font-size: .8rem; color: #f85149; margin-top: .25rem; }
  .summary  { display: flex; gap: 1.5rem; margin: 1.5rem 0; }
  .badge    { padding: .4rem 1rem; border-radius: 4px; font-size: .85rem; font-weight: 600; }
  .badge-gap   { background: #3d1a1a; color: #f85149; }
  .badge-ok    { background: #0d2d0d; color: #3fb950; }
  .badge-total { background: #1c2128; color: #8b949e; }
</style>
</head>
<body>
<h1>AegisLoop — Purple Team Scorecard</h1>
<h2>Continuous Adversarial Control Validation</h2>
<div class="meta">
  <span>Assessment ID: <strong>{{ assessment_id }}</strong></span>
  <span>Generated: <strong>{{ generated }}</strong></span>
  <span>Target: <strong>{{ target }}</strong></span>
</div>

<div class="summary">
  <span class="badge badge-total">Total: {{ findings|length }}</span>
  <span class="badge badge-gap">Gaps: {{ findings|selectattr('is_gap')|list|length }}</span>
  <span class="badge badge-ok">Covered: {{ findings|rejectattr('is_gap')|list|length }}</span>
</div>

<table>
  <thead>
    <tr>
      <th>Technique</th>
      <th>Name</th>
      <th>OWASP</th>
      <th>Severity</th>
      <th>CVSS</th>
      <th>Status</th>
      <th>HTTP</th>
      <th>Latency</th>
    </tr>
  </thead>
  <tbody>
  {% for f in findings %}
    <tr>
      <td><code>{{ f.technique_id }}</code></td>
      <td>
        {{ f.technique_name }}
        {% if f.evidence %}
          <div class="evidence">&#9888; {{ f.evidence }}</div>
        {% endif %}
      </td>
      <td>{{ f.owasp_category }}</td>
      <td class="{{ f.severity }}">{{ f.severity }}</td>
      <td>{{ f.cvss_score }}</td>
      <td class="{{ f.control_status }}">{{ f.control_status }}</td>
      <td>{{ f.status_code or '—' }}</td>
      <td>{{ f.response_time_ms|round|int }} ms</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<p style="margin-top:2rem;font-size:.75rem;color:#30363d;">
  Generated by AegisLoop &mdash; Authorized testing environment only.
</p>
</body>
</html>
"""


def write_report(
    findings: list[FindingResult],
    output_dir: str,
    assessment_id: str,
    target: str,
) -> Path:
    env = Environment(loader=BaseLoader())
    template = env.from_string(_TEMPLATE)

    html = template.render(
        findings=findings,
        assessment_id=assessment_id,
        target=target,
        generated=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    )

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"report_{assessment_id[:8]}.html"
    path.write_text(html, encoding="utf-8")
    log.info("HTML report written to %s", path)
    return path
