from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from ..core.models import FindingResult

log = logging.getLogger(__name__)

# ATT&CK Navigator v4.9 layer schema version
_SCHEMA_VERSION = {
    "attack": "14",
    "navigator": "4.9.1",
    "layer": "4.5",
}


def write_layer(findings: list[FindingResult], output_dir: str, assessment_id: str) -> Path:
    techniques = []
    for f in findings:
        techniques.append(
            {
                "techniqueID": f.technique_id,
                "score": 100 if f.is_gap else 0,
                "color": f.navigator_color,
                "comment": _build_comment(f),
                "enabled": True,
                "metadata": [
                    {"name": "OWASP Category", "value": f.owasp_category},
                    {"name": "Severity", "value": f.severity},
                    {"name": "CVSS Score", "value": str(f.cvss_score)},
                    {"name": "HTTP Status", "value": str(f.status_code or "—")},
                    {"name": "Response Time", "value": f"{f.response_time_ms:.0f} ms"},
                    {"name": "Evidence", "value": f.evidence or "—"},
                ],
            }
        )

    layer = {
        "name": f"AegisLoop — Purple Team Scorecard ({datetime.now(timezone.utc).strftime('%Y-%m-%d')})",
        "versions": _SCHEMA_VERSION,
        "domain": "enterprise-attack",
        "description": (
            f"Continuous control validation layer generated by AegisLoop pipeline. "
            f"Assessment ID: {assessment_id}. "
            f"Green = WAF blocked. Red = control bypassed / gap confirmed. Grey = untested."
        ),
        "filters": {"platforms": ["Linux", "Windows", "Network"]},
        "sorting": 3,
        "layout": {"layout": "flat", "aggregateFunction": "max", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#33cc33", "#ff3333"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "BLOCKED — control effective", "color": "#33cc33"},
            {"label": "BYPASSED — active gap", "color": "#ff3333"},
            {"label": "PARTIAL — mixed telemetry", "color": "#ff9900"},
            {"label": "UNTESTED — no WAF correlation", "color": "#aaaaaa"},
        ],
        "metadata": [
            {"name": "Assessment ID", "value": assessment_id},
            {"name": "Generated", "value": datetime.now(timezone.utc).isoformat()},
        ],
    }

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "purple_matrix.json"
    path.write_text(json.dumps(layer, indent=2))
    log.info("Navigator layer written to %s", path)
    return path


def _build_comment(f: FindingResult) -> str:
    label = {
        "BLOCKED": "COVERED",
        "BYPASSED": "GAP CONFIRMED",
        "PARTIAL": "PARTIAL COVERAGE",
        "UNTESTED": "UNTESTED",
    }[f.control_status]
    base = f"{label} | {f.owasp_category} | CVSS {f.cvss_score}"
    return f"{base} | {f.evidence}" if f.evidence else base
